//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Test.asm
        ///// Created on {0} by the NextGraphics tool from
        ///// patricia curtis at luckyredfish dot com
        ///
        ///TEST_COLOURS:		equ	6
        ///
        ///TestPalette:
        ///			db	%01001001	//	72,72,72
        ///			db	%11111111	//	255,255,255
        ///			db	%11011011	//	218,218,218
        ///			db	%10110110	//	182,182,182
        ///			db	%10010010	//	145,145,145
        ///			db	%01101101	//	109,109,109
        ///
        ///TEST_TILE_SIZE:		equ	32
        ///
        ///TEST_TILES:		equ	4
        ///
        ///TestTile0:
        ///				.db	$00,$11,$11,$00
        ///				.db	$01,$22,$22,$10
        ///				.db	$12,$22,$22,$22
        ///				.db	$12,$14,$22,$23
        ///				.db	$32,$2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Export_Tiles_Asm {
            get {
                return ResourceManager.GetString("Export_Tiles_Asm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Test.asm
        ///// Created on {0} by the NextGraphics tool from
        ///// patricia curtis at luckyredfish dot com
        ///
        ///TEST_COLOURS:		equ	6
        ///
        ///TestPalette:
        ///			db	%01001001	//	72,72,72
        ///			db	%11111111	//	255,255,255
        ///			db	%11011011	//	218,218,218
        ///			db	%10110110	//	182,182,182
        ///			db	%10010010	//	145,145,145
        ///			db	%01101101	//	109,109,109
        ///
        ///TEST_TILE_SIZE:		equ	32
        ///
        ///TEST_TILES:		equ	4
        ///
        ///
        ///				// block data
        ///				// number of tiles (characters) tall
        ///				// number of tiles (characters) wide
        ///					// Palette offse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Export_Tiles_Asm_Binary {
            get {
                return ResourceManager.GetString("Export_Tiles_Asm_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Test.asm
        ///// Created on {0} by the NextGraphics tool from
        ///// patricia curtis at luckyredfish dot com
        ///
        ///TEST_COLOURS:		equ	6
        ///
        ///TestPalette:
        ///			db	%01001001	//	72,72,72
        ///			db	%11111111	//	255,255,255
        ///			db	%11011011	//	218,218,218
        ///			db	%10110110	//	182,182,182
        ///			db	%10010010	//	145,145,145
        ///			db	%01101101	//	109,109,109
        ///
        ///TEST_TILE_SIZE:		equ	32
        ///
        ///TEST_TILES:		equ	4
        ///
        ///
        ///				// block data
        ///				// number of tiles (characters) tall
        ///				// number of tiles (characters) wide
        ///					// Palette offse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Export_Tiles_Asm_Binary_Images {
            get {
                return ResourceManager.GetString("Export_Tiles_Asm_Binary_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Test.asm
        ///// Created on {0} by the NextGraphics tool from
        ///// patricia curtis at luckyredfish dot com
        ///
        ///TEST_COLOURS:		equ	6
        ///
        ///TestPalette:
        ///			db	%01001001
        ///			db	%11111111
        ///			db	%11011011
        ///			db	%10110110
        ///			db	%10010010
        ///			db	%01101101
        ///
        ///TEST_TILE_SIZE:		equ	32
        ///
        ///TEST_TILES:		equ	4
        ///
        ///// Collisions Left Width Top Height
        ///
        ///TestBlock0:		.db	0,0
        ///TestBlock1:		.db	0,1
        ///TestBlock2:		.db	0,2
        ///TestBlock3:		.db	0,3
        ///
        ///TEST_FILE_SIZE	equ	128
        ///TestFile:			dw	TEST_FILE_SIZE
        ///			db	PATH,&quot;game/level1/test. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Export_Tiles_Asm_Binary_NoComments {
            get {
                return ResourceManager.GetString("Export_Tiles_Asm_Binary_NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Test.asm
        ///// Created on {0} by the NextGraphics tool from
        ///// patricia curtis at luckyredfish dot com
        ///
        ///TEST_COLOURS:		equ	6
        ///
        ///TestPalette:
        ///			db	%01001001	//	72,72,72
        ///			db	%11111111	//	255,255,255
        ///			db	%11011011	//	218,218,218
        ///			db	%10110110	//	182,182,182
        ///			db	%10010010	//	145,145,145
        ///			db	%01101101	//	109,109,109
        ///
        ///TEST_TILE_SIZE:		equ	32
        ///
        ///TEST_TILES:		equ	4
        ///
        ///
        ///				// block data
        ///				// number of tiles (characters) tall
        ///				// number of tiles (characters) wide
        ///					// Palette offse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Export_Tiles_Asm_BinaryBlocks {
            get {
                return ResourceManager.GetString("Export_Tiles_Asm_BinaryBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Test.asm
        ///// Created on {0} by the NextGraphics tool from
        ///// patricia curtis at luckyredfish dot com
        ///
        ///TEST_COLOURS:		equ	6
        ///
        ///TestPalette:
        ///			db	%01001001	//	72,72,72
        ///			db	%11111111	//	255,255,255
        ///			db	%11011011	//	218,218,218
        ///			db	%10110110	//	182,182,182
        ///			db	%10010010	//	145,145,145
        ///			db	%01101101	//	109,109,109
        ///
        ///TEST_TILE_SIZE:		equ	32
        ///
        ///TEST_TILES:		equ	4
        ///
        ///
        ///				// block data
        ///				// number of tiles (characters) tall
        ///				// number of tiles (characters) wide
        ///					// Palette offse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Export_Tiles_Asm_BinaryBlocks_Images {
            get {
                return ResourceManager.GetString("Export_Tiles_Asm_BinaryBlocks_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Test.asm
        ///// Created on {0} by the NextGraphics tool from
        ///// patricia curtis at luckyredfish dot com
        ///
        ///TEST_COLOURS:		equ	6
        ///
        ///TestPalette:
        ///			db	%01001001
        ///			db	%11111111
        ///			db	%11011011
        ///			db	%10110110
        ///			db	%10010010
        ///			db	%01101101
        ///
        ///TEST_TILE_SIZE:		equ	32
        ///
        ///TEST_TILES:		equ	4
        ///
        ///
        ///TEST_FILE_SIZE	equ	128
        ///TestFile:			dw	TEST_FILE_SIZE
        ///			db	PATH,&quot;game/level1/test.bin&quot;,0
        ///.
        /// </summary>
        public static string Export_Tiles_Asm_BinaryBlocks_NoComments {
            get {
                return ResourceManager.GetString("Export_Tiles_Asm_BinaryBlocks_NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Test.asm
        ///// Created on {0} by the NextGraphics tool from
        ///// patricia curtis at luckyredfish dot com
        ///
        ///TEST_COLOURS:		equ	6
        ///
        ///TestPalette:
        ///			db	%01001001
        ///			db	%11111111
        ///			db	%11011011
        ///			db	%10110110
        ///			db	%10010010
        ///			db	%01101101
        ///
        ///TEST_TILE_SIZE:		equ	32
        ///
        ///TEST_TILES:		equ	4
        ///
        ///TestTile0:
        ///				.db	$00,$11,$11,$00
        ///				.db	$01,$22,$22,$10
        ///				.db	$12,$22,$22,$22
        ///				.db	$12,$14,$22,$23
        ///				.db	$32,$22,$22,$40
        ///				.db	$04,$33,$54,$45
        ///				.db	$05,$44,$44,$55
        ///				.db	$00,$55,$55,$50
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Export_Tiles_Asm_NoComments {
            get {
                return ResourceManager.GetString("Export_Tiles_Asm_NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Export_Tiles_Bin {
            get {
                object obj = ResourceManager.GetObject("Export_Tiles_Bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Export_Tiles_Image_Blocks {
            get {
                object obj = ResourceManager.GetObject("Export_Tiles_Image_Blocks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Export_Tiles_Image_Tiles {
            get {
                object obj = ResourceManager.GetObject("Export_Tiles_Image_Tiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Export_Tiles_Map {
            get {
                object obj = ResourceManager.GetObject("Export_Tiles_Map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Export_Tiles_Pal {
            get {
                object obj = ResourceManager.GetObject("Export_Tiles_Pal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Export_Tiles_Til {
            get {
                object obj = ResourceManager.GetObject("Export_Tiles_Til", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XML&gt;
        ///  &lt;Project&gt;
        ///    &lt;Name Projectname=&quot;Test&quot; /&gt;
        ///    &lt;Settings blocks=&quot;true&quot; center=&quot;4&quot; xSize=&quot;8&quot; ySize=&quot;8&quot; fourBit=&quot;true&quot; binary=&quot;true&quot; binaryBlocks=&quot;false&quot; Repeats=&quot;false&quot; MirrorX=&quot;false&quot; MirrorY=&quot;false&quot; Rotations=&quot;false&quot; Transparent=&quot;false&quot; Sort=&quot;false&quot; blocksImage=&quot;false&quot; tilesImage=&quot;false&quot; transBlock=&quot;false&quot; transTile=&quot;false&quot; across=&quot;16&quot; accurate=&quot;100&quot; format=&quot;0&quot; textFlips=&quot;false&quot; reduce=&quot;false&quot; /&gt;
        ///    &lt;Palette Mapping=&quot;Custom&quot; Transparent=&quot;0&quot; Used=&quot;6&quot;&gt;
        ///      &lt;Colour0 Red=&quot;72&quot; Green=&quot;72&quot; Blue=&quot;72 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Project_Tiles {
            get {
                return ResourceManager.GetString("Project_Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Project_Tiles_Image1 {
            get {
                object obj = ResourceManager.GetObject("Project_Tiles_Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XML&gt;
        ///  &lt;Project&gt;
        ///	&lt;Name Projectname=&quot;Level1&quot; /&gt;
        ///	&lt;File Path=&quot;C:\tiles.bmp&quot; /&gt;
        ///	&lt;File Path=&quot;/a/file/with/slashes&quot; /&gt;
        ///	&lt;File Path=&quot;\the\file\with\backslashes&quot; /&gt;
        ///	&lt;Settings {0}=&quot;true&quot; center=&quot;4&quot; xSize=&quot;9&quot; ySize=&quot;10&quot; fourBit=&quot;true&quot; binary=&quot;false&quot; binaryBlocks=&quot;true&quot; Repeats=&quot;false&quot; MirrorX=&quot;false&quot; MirrorY=&quot;true&quot; Rotations=&quot;false&quot; Transparent=&quot;false&quot; Sort=&quot;true&quot; blocksImage=&quot;false&quot; tilesImage=&quot;true&quot; transBlock=&quot;true&quot; transTile=&quot;false&quot; across=&quot;5&quot; accurate=&quot;983&quot; format=&quot;{1}&quot; textFlips=&quot;true&quot; reduce=&quot;true&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Project_Tiles_Templated {
            get {
                return ResourceManager.GetString("Project_Tiles_Templated", resourceCulture);
            }
        }
    }
}
