//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextGraphics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentProject {
            get {
                return ((string)(this["RecentProject"]));
            }
            set {
                this["RecentProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asm")]
        public string ExportAssemblerFileExtension {
            get {
                return ((string)(this["ExportAssemblerFileExtension"]));
            }
            set {
                this["ExportAssemblerFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bin")]
        public string ExportBinaryDataFileExtension {
            get {
                return ((string)(this["ExportBinaryDataFileExtension"]));
            }
            set {
                this["ExportBinaryDataFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pal")]
        public string ExportBinaryPaletteFileExtension {
            get {
                return ((string)(this["ExportBinaryPaletteFileExtension"]));
            }
            set {
                this["ExportBinaryPaletteFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("blk")]
        public string ExportBinaryTilesInfoFileExtension {
            get {
                return ((string)(this["ExportBinaryTilesInfoFileExtension"]));
            }
            set {
                this["ExportBinaryTilesInfoFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("map")]
        public string ExportBinaryTileAttributesFileExtension {
            get {
                return ((string)(this["ExportBinaryTileAttributesFileExtension"]));
            }
            set {
                this["ExportBinaryTileAttributesFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tilemap")]
        public string ExportBinaryTilemapFileExtension {
            get {
                return ((string)(this["ExportBinaryTilemapFileExtension"]));
            }
            set {
                this["ExportBinaryTilemapFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("til")]
        public string ExportSpriteAttributesFileExtension {
            get {
                return ((string)(this["ExportSpriteAttributesFileExtension"]));
            }
            set {
                this["ExportSpriteAttributesFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PaletteFormExportFilterIndex {
            get {
                return ((int)(this["PaletteFormExportFilterIndex"]));
            }
            set {
                this["PaletteFormExportFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TilemapRenderTileIndex {
            get {
                return ((bool)(this["TilemapRenderTileIndex"]));
            }
            set {
                this["TilemapRenderTileIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TilemapRenderTileAttributes {
            get {
                return ((bool)(this["TilemapRenderTileAttributes"]));
            }
            set {
                this["TilemapRenderTileAttributes"] = value;
            }
        }
    }
}
