using Microsoft.VisualStudio.TestTools.UnitTesting;

using NextGraphics.Models;
using NextGraphics.Exporting;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

using UnitTests.Data;
using NextGraphics.Exporting.Common;
using System.Drawing;
using System.Text.RegularExpressions;

namespace UnitTests
{
	/*
	 * Note: this test class was created for purposes of extracting exporting code out of main.cs so it doesn't necessarily cover all future exporting capabilities (would be nice to do so though).
	 * 
	 * Test data was generated with original codebase (prior to extracting export from main.cs). Each exported file was added to unit test project as resource and tested against with data generated by exporter class. Assembler output file header was additionally tweaked for each resource so that the date code can be tested - files in resources use `{0}` template which is replaced with the date used on test run. Other files are used exactly as generated by the original codebase.
	 */

	[TestClass]
	public class ExporterTesting
	{
		#region Tiles

		#region Assembler

		[TestMethod]
		public void Tiles_Assembler_FullComments()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTiles(parameters.Time, CommentType.Full));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_NoComments()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.None;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTiles(parameters.Time, CommentType.None));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_BlocksImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.None;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = true;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinary(parameters.BlocksImageStream, DataCreator.TilesImageBlocks(), "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTiles(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_TilesImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.None;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.TilesInfoStream, DataCreator.TilesBlk(), "blk");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.TilesImageTiles(), "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTiles(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_BlocksTilesImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.None;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = true;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.TilesInfoStream, DataCreator.TilesBlk(), "blk");
				VerifyBinary(parameters.BlocksImageStream, DataCreator.TilesImageBlocks(), "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.TilesImageTiles(), "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTiles(parameters.Time, CommentType.None, true));
			});
		}

		#endregion

		#region Assembler+Binary

		[TestMethod]
		public void Tiles_Assembler_Binary_FullComments()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinary(parameters.Time, CommentType.Full));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_Binary_NoComments()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.None;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinary(parameters.Time, CommentType.None));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_Binary_BlocksImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = true;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinary(parameters.BlocksImageStream, DataCreator.TilesImageBlocks(), "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinary(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_Binary_TilesImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.TilesInfoStream, DataCreator.TilesBlk(), "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.TilesImageTiles(), "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinary(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_Binary_BlocksTilesImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = true;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.TilesInfoStream, DataCreator.TilesBlk(), "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinary(parameters.BlocksImageStream, DataCreator.TilesImageBlocks(), "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.TilesImageTiles(), "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinary(parameters.Time, CommentType.None, true));
			});
		}

		#endregion

		#region Assembler+Binary+Blocks

		[TestMethod]
		public void Tiles_Assembler_BinaryBlocks_FullComments()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinary(parameters.TilesStream, DataCreator.TilesTil(), "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinaryAndBlocks(parameters.Time, CommentType.Full));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_BinaryBlocks_NoComments()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.None;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinary(parameters.TilesStream, DataCreator.TilesTil(), "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinaryAndBlocks(parameters.Time, CommentType.None));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_BinaryBlocks_BlocksImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = true;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinary(parameters.TilesStream, DataCreator.TilesTil(), "til");
				VerifyBinaryIsEmpty(parameters.TilesInfoStream, "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinary(parameters.BlocksImageStream, DataCreator.TilesImageBlocks(), "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinaryAndBlocks(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_BinaryBlocks_TilesImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = false;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinary(parameters.TilesStream, DataCreator.TilesTil(), "til");
				VerifyBinary(parameters.TilesInfoStream, DataCreator.TilesBlk(), "blk");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.TilesImageTiles(), "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinaryAndBlocks(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Tiles_Assembler_BinaryBlocks_BlocksTilesImage()
		{
			TestTiles((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Tiles;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = true;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.PaletteStream, DataCreator.TilesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.TilesBin(), "bin");
				VerifyBinary(parameters.TilesInfoStream, DataCreator.TilesBlk(), "blk");
				VerifyBinary(parameters.TilesStream, DataCreator.TilesTil(), "til");
				VerifyBinary(parameters.MapStream, DataCreator.TilesMap(), "map");
				VerifyBinary(parameters.BlocksImageStream, DataCreator.TilesImageBlocks(), "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.TilesImageTiles(), "tiles image");
				VerifyAssembler(parameters, DataCreator.AssemblerTilesAndBinaryAndBlocks(parameters.Time, CommentType.None, true));
			});
		}

		#endregion

		#endregion

		#region Sprites

		#region Assembler

		[TestMethod]
		public void Sprites_Assembler_FullComments()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSprites(parameters.Time, CommentType.Full));
			});
		}
		
		[TestMethod]
		public void Sprites_Assembler_NoComments()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.None;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSprites(parameters.Time, CommentType.None));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_BlocksImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.None;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = true;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify (note no block image is generated for sprites)
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSprites(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_TilesImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.None;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.SpritesImageTiles(), "tiles image");
				VerifyBinaryArray(14, (i) => DataCreator.SpritesImageBlock(i), parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSprites(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_BlocksTilesImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.None;
				model.BinaryOutput = false;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = true;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify (note no block image is generated for sprites)
				VerifyBinaryIsEmpty(parameters.PaletteStream, "pal");
				VerifyBinaryIsEmpty(parameters.BinaryStream, "bin");
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.SpritesImageTiles(), "tiles image");
				VerifyBinaryArray(14, (i) => DataCreator.SpritesImageBlock(i), parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSprites(parameters.Time, CommentType.None, true));
			});
		}

		#endregion

		#region Assembler+Binary

		[TestMethod]
		public void Sprites_Assembler_Binary_FullComments()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinary(parameters.Time, CommentType.Full));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_Binary_NoComments()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.None;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinary(parameters.Time, CommentType.None));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_Binary_BlocksImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = true;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinary(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_Binary_TilesImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = false;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.SpritesImageTiles(), "tiles image");
				VerifyBinaryArray(14, (i) => DataCreator.SpritesImageBlock(i), parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinary(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_Binary_BlocksTilesImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = false;
				model.BlocksAsImage = true;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinaryIsEmpty(parameters.TilesStream, "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.SpritesImageTiles(), "tiles image");
				VerifyBinaryArray(14, (i) => DataCreator.SpritesImageBlock(i), parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinary(parameters.Time, CommentType.None, true));
			});
		}

		#endregion

		#region Assembler+Binary+Blocks

		[TestMethod]
		public void Sprites_Assembler_BinaryBlocks_FullComments()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.TilesStream, DataCreator.SpritesTil(), "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinaryAndBlocks(parameters.Time, CommentType.Full));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_BinaryBlocks_NoComments()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.None;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = false;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.TilesStream, DataCreator.SpritesTil(), "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinaryAndBlocks(parameters.Time, CommentType.None));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_BinaryBlocks_BlocksImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = true;
				model.TilesAsImage = false;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.TilesStream, DataCreator.SpritesTil(), "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinaryIsEmpty(parameters.TilesImageStream, "tiles image");
				VerifyBinaryArrayIsEmpty(20, parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinaryAndBlocks(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_BinaryBlocks_TilesImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = false;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.TilesStream, DataCreator.SpritesTil(), "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.SpritesImageTiles(), "tiles image");
				VerifyBinaryArray(14, (i) => DataCreator.SpritesImageBlock(i), parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinaryAndBlocks(parameters.Time, CommentType.None, true));
			});
		}

		[TestMethod]
		public void Sprites_Assembler_BinaryBlocks_BlocksTilesImage()
		{
			TestSprites((model, parameters, exporter) =>
			{
				// setup
				model.OutputType = OutputType.Sprites;
				model.CommentType = CommentType.Full;
				model.BinaryOutput = true;
				model.BinaryBlocksOutput = true;
				model.BlocksAsImage = true;
				model.TilesAsImage = true;

				// execute
				exporter.Remap();
				exporter.Export();

				// verify
				VerifyBinary(parameters.TilesStream, DataCreator.SpritesTil(), "til");
				VerifyBinary(parameters.PaletteStream, DataCreator.SpritesPal(), "pal");
				VerifyBinary(parameters.BinaryStream, DataCreator.SpritesBin(), "bin");
				VerifyBinaryIsEmpty(parameters.MapStream, "map");
				VerifyBinaryIsEmpty(parameters.BlocksImageStream, "blocks image");
				VerifyBinary(parameters.TilesImageStream, DataCreator.SpritesImageTiles(), "tiles image");
				VerifyBinaryArray(14, (i) => DataCreator.SpritesImageBlock(i), parameters.BlockImageStream, "block image");
				VerifyAssembler(parameters, DataCreator.AssemblerSpritesAndBinaryAndBlocks(parameters.Time, CommentType.None, true));
			});
		}

		#endregion

		#endregion

		#region Creating

		private void TestTiles(Action<MainModel, ExportParameters, Exporter> tester)
		{
			Test(
				DataCreator.XmlDocumentTiles(),
				DataCreator.ImageTiles1(),
				tester);
		}

		private void TestSprites(Action<MainModel, ExportParameters, Exporter> tester)
		{
			Test(
				DataCreator.XmlDocumentSprites(),
				DataCreator.ImageSprites1(),
				tester);
		}

		private void Test(XmlDocument sourceDocument, Bitmap sourceBitmap, Action<MainModel, ExportParameters, Exporter> tester)
		{
			// We use memory streams so that we can later on examine the results without writing out files - faster and more predictable. 
			using (
				MemoryStream sourceStream = new MemoryStream(),
				binaryStream = new MemoryStream(),
				paletteStream = new MemoryStream(),
				mapStream = new MemoryStream(),
				tilesStream = new MemoryStream(),
				tilesImageStream = new MemoryStream(),
				tilesInfoStream = new MemoryStream(),
				blocksImageStream = new MemoryStream())
			{
				var blockStreams = new MemoryStream[40];

				// We want streams to be "constant", created only once per test and then reused whenever anyone calls out the closures.
				var parameters = new ExportParameters
				{
					Time = DateTime.Now,

					ExportCallbacks = new ExportCallbacksImpl(),

					SourceStream = () => sourceStream,
					PaletteStream = () => paletteStream,
					BinaryStream = () => binaryStream,
					MapStream = () => mapStream,
					TilesStream = () => tilesStream,
					TilesInfoStream = () => tilesInfoStream,
					TilesImageStream = () => tilesImageStream,
					BlocksImageStream = () => blocksImageStream,
					BlockImageStream = (i) =>
					{
						if (blockStreams[i] == null)
						{
							blockStreams[i] = new MemoryStream();
						}
						return blockStreams[i];
					},
				};

				// We load default data and rely on each test to set it up as needed. This sets up model with default parameters, but we can later change them as needed in each specific test.
				var model = DataCreator.LoadModel(sourceDocument);
				model.AddImage(new SourceImage("image1", sourceBitmap));

				// Prepare exporter.
				var exporter = new Exporter(model, parameters);

				// Call out tester closure to actually perform the test.
				tester(model, parameters, exporter);

				foreach (var stream in blockStreams)
				{
					if (stream != null)
					{
						stream.Dispose();
					}
				}
			}
		}

		#endregion

		#region Verifying

		private void VerifyAssembler(ExportParameters parameters, string expected) 
		{
			// Prepare new memory stream as original one was already closed after writing the output.
			using (var actual = new MemoryStream(((MemoryStream)parameters.SourceStream()).ToArray()))
			{
				// This code trims all empty lines so we can compare just data.
				var expectedLines = expected.ToLines().Where(line => line.Trim().Length > 0).ToList();
				var actualLines = actual.ToLines().Where(line => line.Trim().Length > 0).ToList();

				// Note: we could assert on both lists direclty, but then assertion errors are not very helpful...
				Assert.AreEqual(expectedLines.Count, actualLines.Count, $"assembler lines count is different");

				string SanitizedLine(string line)
				{
					return Regex.Replace(line, @"\s+", " ");
				}

				for (var i=0; i<expectedLines.Count; i++)
				{
					// We replace all whitespace with single space to match only on actual data.
					var expectedLine = SanitizedLine(expectedLines[i]);
					var actualLine = SanitizedLine(actualLines[i]);
					Assert.AreEqual(expectedLine, actualLine, $"assembler line {i + 1} different");
				}
			}
		}

		private void VerifyBinary(Func<Stream> stream, byte[] expected, string explanation = "")
		{
			var actual = ((MemoryStream)stream()).ToArray();
			Assert.AreEqual(expected.Length, actual.Length, $"{explanation} size is different");
				
			for (var i=0; i<expected.Length; i++)
			{
				var expectedByte = expected[i];
				var actualByte = actual[i];

				Assert.AreEqual(expectedByte, actualByte, $"{explanation} byte {i} is different");
			}
		}

		private void VerifyBinaryArray(int count, Func<int, byte[]> expected, Func<int, Stream> streams, string explanation = "")
		{
			// If no stream was produced, we assume it's indeed emtpy.
			if (streams == null) return;

			for (int i = 0; i < count; i++)
			{
				var actualStream = streams(i);
				var expectedData = expected(i);

				VerifyBinary(() => actualStream, expectedData, $"{explanation}[{i}]");
			}
		}

		private void VerifyBinaryIsEmpty(Func<Stream> stream, string explanation = "")
		{
			// If no stream  was produces, we assume it's indeed empty...
			if (stream == null) return;

			using (var actual = new MemoryStream(((MemoryStream)stream()).ToArray()))
			{
				Assert.AreEqual(0, actual.Length, $"{explanation} size is not zero");
			}
		}

		private void VerifyBinaryArrayIsEmpty(int count, Func<int, Stream> streams, string explanation = "")
		{
			// If no stream was produced, we assume it's indeed emtpy.
			if (streams == null) return;

			for (int i=0; i<count; i++)
			{
				using (var actual = new MemoryStream(((MemoryStream)streams(i)).ToArray()))
				{
					Assert.AreEqual(0, actual.Length, $"{explanation}[{i}] size is not zero");
				}
			}
		}

		#endregion

		#region Declarations

		private class ExportCallbacksImpl : ExportCallbacks
		{
			public void OnExportStarted()
			{
			}

			public void OnExportCompleted()
			{
			}

			public string OnExportTilesInfoFilename()
			{
				return DataCreator.TilesBlkFilename();
			}

			public byte OnExportFourBitColourConverter(byte proposed)
			{
				return proposed;
			}

			public byte OnExportPaletteOffsetMapper(byte proposed)
			{
				return proposed;
			}
		}

		#endregion
	}
}
